---
  - name: Upgrade packages
    become: true
    apt: upgrade=dist update_cache=true autoremove=true

  - name: Install packages
    become: true
    apt: pkg={{ item }} state=latest update_cache=true
    with_items: "{{ server.packages }}"
    when: server.packages is defined

  - name: Set timezone to {{ server.timezone }}
    become: true
    timezone: name={{ server.timezone }}

  - name: Generate locale {{ server.locale }}
    locale_gen: name={{ server.locale }} state=present
