php:
    repository:
        key: https://packages.sury.org/php/apt.gpg
        url: deb https://packages.sury.org/php stretch main

    version: 7.1
    extensions:
      - fpm
      - cli
      - intl
      - opcache
      - mbstring
      - pgsql
      - xdebug

    install_composer: true

    fpm_pools:
        - { filename: www.conf, user: www, group: www }

webserver:
    user: www
    group: www

server:
    timezone: 'UTC'
